<?php
	
/*
	Question2Answer (c) Gideon Greenspan
	http://www.question2answer.org/

	Copyright (C) 2013 Sander Lepik
	
	File: qa-lang/et/qa-lang-main.php
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 vastus',
		'1_comment' => '1 kommentaar',
		'1_day' => '1 päev',
		'1_disliked' => '1 vastuhääl',
		'1_flag' => '1 märgistus',
		'1_hour' => '1 tund',
		'1_liked' => '1 poolthääl',
		'1_minute' => '1 minut',
		'1_month' => '1 kuu',
		'1_point' => '1 punkt',
		'1_question' => '1 küsimus',
		'1_second' => '1 sekund',
		'1_tag' => '1 silt',
		'1_user' => '1 kasutaja',
		'1_view' => '1 vaatamine',
		'1_vote' => '1 hääl',
		'1_week' => '1 nädal',
		'1_year' => '1 aasta',
		'add_category_x_favorites' => 'Lisa kategooria "^" lemmikutesse',
		'add_favorites' => 'Lisa lemmikutesse',
		'add_tag_x_favorites' => 'Lisa silt "^" lemmikutesse',
		'all_categories' => 'Kõik kategooriad',
		'anonymous' => 'anonüümne',
		'answer_edited' => 'vastust on muudetud',
		'answer_reshown' => 'vastus on uuesti nähtavaks tehtud',
		'answer_selected' => 'vastus on valitud',
		'answered_qs_in_x' => 'Enim vastatud küsimused kategoorias "^"',
		'answered_qs_title' => 'Enim vastatud küsimused',
		'answered' => 'vastatud',
		'asked_related_q' => 'küsitud siduv küsimus',
		'asked' => 'küsitud',
		'by_x' => '- ^',
		'cancel_button' => 'Loobu',
		'closed' => 'suletud',
		'comment_edited' => 'kommentaari on muudetud',
		'comment_moved' => 'kommentaar on liigutatud',
		'comment_reshown' => 'kommentaar on uuesti nähtavaks tehtud',
		'commented' => 'kommenteeritud',
		'date_day_min_digits' => 1, // 1 or 2
		'date_format_other_years' => '^day. ^month ^year',
		'date_format_this_year' => '^day. ^month',
		'date_month_1' => 'jaan',
		'date_month_2' => 'veebr',
		'date_month_3' => 'märts',
		'date_month_4' => 'apr',
		'date_month_5' => 'mai',
		'date_month_6' => 'juuni',
		'date_month_7' => 'juuli',
		'date_month_8' => 'aug',
		'date_month_9' => 'sept',
		'date_month_10' => 'okt',
		'date_month_11' => 'nov',
		'date_month_12' => 'dets',
		'date_year_digits' => 4, // 2 or 4
		'edited' => 'muudetud',
		'field_required' => 'Palun sisesta midagi sellele väljale',
		'general_error' => 'Serveri viga - palun proovi uuesti.',
		'hidden' => 'peidetud',
		'highest_users' => 'Suuremate punktidega kasutajad',
		'hot_qs_in_x' => 'Kuumad küsimused kategoorias "^"',
		'hot_qs_title' => 'Kuumad küsimused',
		'image_not_read' => 'Pilti polnud võimalik lugeda. Palun kasuta üht järgmistest vormingutest: ^',
		'image_too_big_x_pc' => 'See pilt on liiga suur. Vähenda ^% peale ja proovi siis uuesti.',
		'in_category_x' => 'kategoorias ^',
		'ip_address_x' => 'IP-aadress ^',
		'logged_in_x' => 'Tere, ^',
		'max_length_x' => 'Maksimaalne pikkus on ^ tähemärki',
		'me' => 'mina',
		'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Palun lisa rohkem infot - vähemalt ^ tähemärki',
		'max_upload_size_x' => 'Maksimaalne üleslaadimise suurus on ^',
		'moved' => 'liigutatud',
		'nav_account' => 'Konto',
		'nav_activity' => 'Kogu tegevus',
		'nav_admin' => 'Administreerimine',
		'nav_ask' => 'Küsi',
		'nav_categories' => 'Kategooriad',
		'nav_feedback' => 'Anna tagasisidet',
		'nav_home' => 'Avaleht',
		'nav_hot' => 'Kuum!',
		'nav_login' => 'Logi sisse',
		'nav_logout' => 'Logi välja',
		'nav_most_answers' => 'Enim vastatud',
		'nav_most_recent' => 'Hiljutised',
		'nav_most_views' => 'Enim vaadatud',
		'nav_most_votes' => 'Enim hääletatud',
		'nav_no_answer' => 'Vastuseta',
		'nav_no_selected_answer' => 'Valitud vastuseta',
		'nav_no_upvoted_answer' => 'Üleshääletatud vastuseta',
		'nav_qa' => 'Avaleht',
		'nav_qs' => 'Küsimused',
		'nav_register' => 'Registreeri',
		'nav_tags' => 'Sildid',
		'nav_unanswered' => 'Vastuseta',
		'nav_updates' => 'Minu uuendused',
		'nav_users' => 'Kasutajad',
		'no_active_users' => 'Aktiivseid kasutajaid ei leitud',
		'no_answers_found' => 'Vastuseid ei leitud',
		'no_answers_in_x' => 'Vasutseid kategoorias "^" ei leitud',
		'no_categories_found' => 'Kategooriaid ei leitud',
		'no_category' => 'Kategooriat pole',
		'no_comments_found' => 'Kommentaare ei leitud',
		'no_comments_in_x' => 'Kommentaare kategoorias "^" ei leitud',
		'no_questions_found' => 'Küsimusi ei leitud',
		'no_questions_in_x' => 'Küsimusi kategoorias "^" ei leitud',
		'no_related_qs_title' => 'Seostuvaid küsimusi ei leitud',
		'no_results_for_x' => 'Otsingule "^" ei leitud vastust',
		'no_tags_found' => 'Silte ei leitud',
		'no_una_questions_found' => 'Vastuseta küsimusi ei leitud',
		'no_una_questions_in_x' => 'Vastuseta küsimusi kategoorias "^" ei leitud',
		'no_unselected_qs_found' => 'Valitud vastuseta küsimusi ei leitud',
		'no_unupvoteda_qs_found' => 'Üleshääletatud vastuseta küsimusi ei leitud',
		'page_label' => 'Leht:',
		'page_next' => 'järgmine',
		'page_not_found' => 'Lehte ei leitud',
		'page_prev' => 'eelmine',
		'popular_tags' => 'Populaarseimad sildid',
		'questions_tagged_x' => 'Hiljutised küsimused sildiga "^"',
		'recategorized' => 'kategooria muudetud',
		'recent_activity_in_x' => 'Hiljutine tegevus kategoorias "^"',
		'recent_activity_title' => 'Hiljutine tegevus',
		'recent_as_in_x' => 'Hiljuti vastatud küsimused kategoorias "^"',
		'recent_as_title' => 'Hiljuti vastatud küsimused',
		'recent_cs_in_x' => 'Hiljuti kommenteeritud küsimused kategoorias "^"',
		'recent_cs_title' => 'Hiljuti kommenteeritud küsimused',
		'recent_qs_as_in_x' => 'Hiljutised küsimused ja vastused kategoorias "^"',
		'recent_qs_as_title' => 'Hiljutised küsimused ja vastused',
		'recent_qs_in_x' => 'Hiljutised küsimused kategoorias "^"',
		'recent_qs_title' => 'Hiljutised küsimused',
		'related_qs_title' => 'Seostuvad küsimused',
		'remove_favorites' => 'Eemalda lemmikutest',
		'remove_x_favorites' => 'Eemalda "^" lemmikutest',
		'reopened' => 'taasavatud',
		'reshown' => 'taasavalikustatud',
		'results_for_x' => 'Tulemused otsingule "^"',
		'retagged' => 'uuesti sildistatud',
		'save_button' => 'Salvesta muudatused',
		'search_button' => 'Otsi',
		'search_explanation' => 'Palun sisesta otsingukasti mingi tekst ja proovi siis uuesti.',
		'search_title' => 'Otsingutulemused',
		'selected' => 'valitud',
		'send_button' => 'Saada',
		'suggest_ask' => 'Aita algust teha ja ^1esita küsimus^2.',
		'suggest_category_qs' => 'Et rohkem näha, klõpsa ^1kõik küsimused selles kategoorias^2.',
		'suggest_qs_tags' => 'Et rohkem näha, vaata ^1kõiki küsimusi^2 või ^3popularseid silte^4.',
		'suggest_qs' => 'Et rohkem näha, vaata ^1kõiki küsimusi^2.',
		'unanswered_qs_in_x' => 'Vastuseta küsimused kategoorias "^"',
		'unanswered_qs_title' => 'Hiljutised vastuseta küsimused',
		'unselected_qs_in_x' => 'Valitud vastuseta küsimused kategoorias "^"',
		'unselected_qs_title' => 'Hiljutised valitud vastuseta küsimused',
		'unupvoteda_qs_in_x' => 'Üleshääletatud vastuseta küsimused kategoorias "^"',
		'unupvoteda_qs_title' => 'Hiljutised üleshääletatud vastuseta küsimused',
		'upload_limit' => 'Liiga palju üleslaadimisi - proovi tunni pärast uuesti',
		'view_q_must_be_approved' => 'Küsimuste nägemiseks peab sinu konto kõigepealt heakskiidu saama.',
		'view_q_must_confirm' => 'Küsimuste nägemiseks ^5kinnita palun oma e-posti aadress^6.',
		'view_q_must_login' => 'Küsimuste nägemiseks ^1logi sisse^2 või ^3registreeru^4.',
		'viewed_qs_in_x' => 'Enim vaadatud küsimused kategoorias "^"',
		'viewed_qs_title' => 'Enim vaadatud küsimused',
		'vote_disabled_approve' => 'Hääletamiseks peab sinu konto kõigepealt heakskiidu saama',
		'vote_disabled_down' => 'Mahahääletamine on võimalik ainult osade kasutajate jaoks',
		'vote_disabled_down_approve' => 'Mahahääletamiseks peab sinu konto kõigepealt heakskiidu saama',
		'vote_disabled_hidden_a' => 'Peidetud vastuseid ei saa hääletada',
		'vote_disabled_hidden_q' => 'Peidetud küsimusi ei saa hääletada',
		'vote_disabled_level' => 'Hääletada saavad ainult osad kasutajad',
		'vote_disabled_my_a' => 'Enda vastuseid ei saa hääletada',
		'vote_disabled_my_q' => 'Enda küsimusi ei saa hääletada',
		'vote_disabled_q_page_only' => 'Hääletamiseks vaata kõigepealt küsimust',
		'vote_down_must_confirm' => 'Mahahääletamiseks ^5kinnita kõigepealt oma e-posti aadress^6.',
		'vote_down_popup' => 'Mahahääletamiseks klõpsa',
		'vote_limit' => 'Liiga palju hääli vastu võetud - palun proovi tunni pärast uuesti',
		'vote_must_confirm' => 'Hääletamiseks ^5kinnita kõigepealt oma e-posti aadress^6.',
		'vote_must_login' => 'Hääletamiseks ^1logi sisse^2 või ^3registreeru^4.',
		'vote_not_allowed' => 'Selle hääletamine pole lubatud',
		'vote_up_popup' => 'Ülsehääletamiseks klõpsa',
		'voted_down_popup' => 'Oled selle mahahääletanud - hääle eemaldamiseks klõpsa',
		'voted_qs_in_x' => 'Kõrgemailt hääletatud küsimused kategoorias "^"',
		'voted_qs_title' => 'Kõrgemailt hääletatud küsimused',
		'voted_up_popup' => 'Oled selle üleshääletanud - hääle eemaldamiseks klõpsa',
		'written' => '', // blank in English - placeholder for other languages
		'x_ago' => '^ tagasi',
		'x_answers' => '^ vastust',
		'x_comments' => '^ kommentaari',
		'x_days' => '^ päeva',
		'x_disliked' => '^ vastuhäält',
		'x_flags' => '^ märgistust',
		'x_hours' => '^ tundi',
		'x_liked' => '^ poolthäält',
		'x_minutes' => '^ minutit',
		'x_months' => '^ kuud',
		'x_points' => '^ punkti',
		'x_questions' => '^ küsimust',
		'x_seconds' => '^ sekundit',
		'x_tags' => '^ silti',
		'x_users' => '^ kasutajat',
		'x_views' => '^ vaatamist',
		'x_votes' => '^ häält',
		'x_weeks' => '^ nädalat',
		'x_years' => '^ aastat',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
