<?php
	
/*
	Question2Answer (c) Gideon Greenspan
	http://www.question2answer.org/

	Copyright (C) 2014 Sander Lepik
	
	File: qa-lang/et/qa-lang-options.php
	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'allow_change_usernames' => 'Postitustega kasutajatel on kasutajanime muutmine lubatud:',
		'allow_close_questions' => 'Küsimuste käsitsi sulgemine on lubatud:',
		'allow_login_email_only' => 'Sisselogimine toimub ainult e-posti aadressiga (mitte kasutajanimega):', 
		'allow_multi_answers' => 'Lubatakse mitu vastust kasutaja kohta:',
		'allow_no_category' => 'Lubatakse kategooriata küsimused',
		'allow_no_sub_category' => 'Lubatakse küsimused, millel on kategooria, aga puudub alamkategooria',
		'allow_private_messages' => 'Privaatsõnumid kasutajate vahel lubatakse:',
		'allow_user_walls' => 'Seinapostitused kasutajate profiilidel lubatakse:',
		'allow_self_answer' => 'Kasutajatel lubatakse vastata enda küsimusele:',
		'allow_view_q_bots' => 'Otsingumootoritel lubatakse vaadata küsimuste lehti',
		'approve_user_required' => 'Kõik uued kasutajad peavad saama heakskiidu:',
		'avatar_allow_gravatar' => 'Avatarid ^1Gravatarist^2 lubatakse:',
		'avatar_allow_upload' => 'Kasutajatel lubatakse avataride üleslaadimine:',
		'avatar_default_show' => 'Vaikeavatar:',
		'avatar_message_list_size' => 'Avataride suurus kirjade nimekirjades:',
		'avatar_profile_size' => 'Avataride suurus profiili lehel:',
		'avatar_q_list_size' => 'Avataride suurus küsimuste nimekirjades:',
		'avatar_q_page_a_size' => 'Avataride suurus vastustes:',
		'avatar_q_page_c_size' => 'Avataride suurus kommentaarides:',
		'avatar_q_page_q_size' => 'Avataride suurus küsimustes:',
		'avatar_store_size' => 'Maksimaalne salvestatava avatari suurus:',
		'avatar_users_size' => 'Avataride suurus kasutajate edetabelis:',
		'block_bad_words' => 'Tsenseeritud sõnad - eralda tühikute või komadega:',
		'block_ips_write' => 'Blokeeritud IP-aadressid - eralda tühikute või komadega:',
		'captcha_module' => 'Kasutatakse järgnevat robotilõksu modulit:',
		'captcha_on_anon_post' => 'Robotilõksu kasutatakse anonüümsel postitamisel:',
		'captcha_on_feedback' => 'Robotilõksu kasutatakse tagasiside andmise vormil:',
		'captcha_on_register' => 'Robotilõksu kasutatakse registreerumisel:',
		'captcha_on_reset_password' => 'Robotilõksu kasutatakse parooli lähtestamise vormil:',
		'captcha_on_unapproved' => 'Robotilõksu kasutatakse heakskiiduta kasutajate jaoks:',
		'captcha_on_unconfirmed' => 'Robotilõksu kasutatakse kinnitamata e-posti aadressi korral:',
		'columns_tags' => 'Veerge siltide lehel:',
		'columns_users' => 'Veerge kasutajate lehel:',
		'comment_on_as' => 'Vastuste kommenteerimine lubatakse:',
		'comment_on_qs' => 'Küsimuste kommenteerimine lubatakse:',
		'confirm_user_emails' => 'Kasutajatelt nõutakse e-posti aadressi kinnitamist:',
		'confirm_user_required' => 'Kõik uued kasutajad peavad oma e-posti aadressi kinnitama:',
		'custom_home_content' => 'Avalehe sisu - HTML on lubatud:',
		'custom_home_heading' => 'Avalehe pealkiri:',
		'default_privacy' => 'Privaatsusest: sinu e-posti aadressi ei jagata ega müüda kolmandatele osapooltele.',
		'default_sidebar' => "Tere tulemast keskkonda \"^\", kus saad esitada küsimusi ning saada vastuseid teistelt kogukonna liikmetelt.",
		'default_subject' => 'Kiri keskkonnalt "^"',
		'default_suffix' => 'Q&A',
		'do_ask_check_qs' => 'Küsimuse esitamisel kontrollitakse sarnaste küsimuste olemasolu:',
		'do_close_on_select' => 'Parima vastuse valimisel küsimus suletakse:',
		'do_complete_tags' => 'Kirjutamisel kuvatakse sobivaid silte:',
		'do_count_q_views' => 'Küsimuste vaatamise kordi loendatakse:',
		'do_example_tags' => 'Kuvatakse küsimusel baseeruvaid näidissilte:',
		'editor_for_as' => 'Tekstiredaktori režiim vastuste jaoks:',
		'editor_for_cs' => 'Tekstiredaktori režiim kommentaarida jaoks:',
		'editor_for_qs' => 'Tekstiredaktori režiim küsimuste jaoks:',
		'email_privacy' => 'Privaatsuse info e-posti aadresside jaoks - HTML on lubatud:',
		'extra_field_active' => 'Kohandatud väli lisainfo jaoks küsimuse esitamise vormil:',
		'extra_field_display_label' => 'Kohandatud välja sisu kuvatakse küsimuste lehtedel järgneva pealkirjaga:',
		'extra_field_display' => 'Kohandatud välja sisu kuvatakse küsimuste lehtedel',
		'feed_for_activity' => 'Uudistevoog hiljutise tegevuse jaoks:',
		'feed_for_hot' => 'Uudistevoog kuumade küsimuste jaoks:',
		'feed_for_qa' => 'Uudistevoog hiljutiste küsimuste ja vastuste jaoks:',
		'feed_for_questions' => 'Uudistevoog hiljutiste küsimuste jaoks:',
		'feed_for_search' => 'Uudistevood otsingutulemuste jaoks:',
		'feed_for_tag_qs' => 'Uudistevood iga sildi küsimuste jaoks:',
		'feed_for_unanswered' => 'Uudistevoog vastuseta küsimuste jaoks:',
		'feed_full_text' => 'Uudistevood sisaldavad täielikku teksti:',
		'feed_number_items' => 'Uudistevoogude maksimaalne pikkus:',
		'feed_per_category' => 'Eraldi uudistevoog iga kategooria kohta:',
		'feedback_email' => 'E-posti aadress administraatorile mõeldud kirjade jaoks - ei kuvata kasutajatele:',
		'feedback_enabled' => 'Lubatakse tagasiside saatmise leht',
		'flagging_hide_after' => 'Automaatselt peidetakse postitused, mis on saanud:',
		'flagging_notify_every' => 'Saadetakse uus e-kiri, kui on lisandunud järgmised:',
		'flagging_notify_first' => 'Saadetakse e-kiri, kui postitus saab:',
		'flagging_of_posts' => 'Postituste märgistamine lubatakse:',
		'follow_on_as' => 'Lubatakse vastustega seostatud küsimuste esitamine:',
		'from_email' => 'Saidi nime alt saadetavate kirjade saatja aadress:',
		'hot_weight_a_age' => 'Küsimusel on uus vastus:',
		'hot_weight_answers' => 'Küsimusel on mitu vastust:',
		'hot_weight_q_age' => 'Küsimus on uus:',
		'hot_weight_views' => 'Küsimusel on palju vaatamisi:',
		'hot_weight_votes' => 'Küsimusel on palju üleshääli:',
		'links_in_new_window' => 'Lingitud URLid avatakse uues aknas:',
		'logo_height' => 'Logo kõrgus:',
		'logo_show' => 'Lehe päises kuvatakse logo',
		'logo_url' => 'Logo URL - absoluutne aadress või suhteline Q2A juurkausta suhtes:',
		'logo_width' => 'Logo laius:',
		'mailing_body' => 'Sisu tekst:',
		'mailing_enabled' => 'Lubatakse kirjade saatmine kõigile kasutajatele',
		'mailing_from_email' => 'Saatja e-posti aadress:',
		'mailing_from_name' => 'Saatja nimi:',
		'mailing_per_minute' => 'Maksimaalne saatmise tihedus:',
		'mailing_subject' => 'Teema:',
		'match_1' => 'kitsaim',
		'match_2' => 'kitsam',
		'match_3' => 'vaikimisi',
		'match_4' => 'laiem',
		'match_5' => 'kõige laiem',
		'match_ask_check_qs' => 'Sarnaste küsimuste sobivuse haardeulatus:',
		'match_example_tags' => 'Näidissiltide sobivuse haardeulatus:',
		'match_related_qs' => 'Seostuvate küsimuste sobivuse haardeulatus:',
		'max_len_q_title' => 'Küsimuse pealkirja maksimaalne pikkus:',
		'max_num_q_tags' => 'Maksimaalne siltide arv:',
		'max_rate_ip_as' => 'Vastamise limiit:',
		'max_rate_ip_cs' => 'Kommenteerimise limiit:',
		'max_rate_ip_flags' => 'Postituste märgistamise limiit:',
		'max_rate_ip_logins' => 'Sisselogimise limiit:',
		'max_rate_ip_messages' => 'Privaatsõnumite ja seinapostituste kirjutamise limiit:',
		'max_rate_ip_qs' => 'Küsimuste esitamise limiit:',
		'max_rate_ip_registers' => 'Kasutajaks registreerumise limiit:',
		'max_rate_ip_uploads' => 'Failide üleslaadimise limiit:',
		'max_rate_ip_votes' => 'Hääletamise limiit:',
		'max_rate_user_as' => 'Maksimaalne arv vastuseid tunnis ühe kasutaja kohta:',
		'max_rate_user_cs' => 'Maksimaalne arv kommentaare tunnis ühe kasutaja kohta:',
		'max_rate_user_flags' => 'Maksimaalne arv märgistamisi tunnis ühe kasutaja kohta:',
		'max_rate_user_messages' => 'Maksimaalne arv privaatsõnumeid tunnis ühe kasutaja kohta:',
		'max_rate_user_qs' => 'Maksimaalne arv küsimusi tunnis ühe kasutaja kohta:',
		'max_rate_user_uploads' => 'Maksimaalne arv üleslaadimisi tunnis ühe kasutaja kohta:',
		'max_rate_user_votes' => 'Maksimaalne arv hääletusi tunnis ühe kasutaja kohta:',
		'min_len_a_content' => 'Vastuse minimaalne pikkus:',
		'min_len_c_content' => 'Kommentaari minimaalne pikkus:',
		'min_len_q_content' => 'Küsimuse sisu minimaalne pikkus:',
		'min_len_q_title' => 'Küsimuse pealkirja minimaalne pikkus:',
		'min_num_q_tags' => 'Minimaalne siltide arv:',
		'moderate_anon_post' => 'Anonüümsete postituste korral kasutatakse modereerimist:',
		'moderate_by_points' => 'Väheste punktidega kasutajate korral kasutatakse modereerimist:',
		'moderate_edited_again' => 'Postitused vajavad pärast muutmist uut modereerimist:',
		'moderate_notify_admin' => 'Saadetakse e-kiri, kui postitus ootab modereerimist:',
		'moderate_points_limit' => 'Kasutatakse modereerimist, kui kasutajal on vähem kui:',
		'moderate_unapproved' => 'Kasutatakse modereerimist, kui kasutaja pole veel heakskiitu saanud:',
		'moderate_unconfirmed' => 'Kasutatakse modereerimist, kui kasutaja pole e-posti kinnitanud:',
		'moderate_update_time' => 'Modereeritud postitustel kuvatakse:',
		'moderate_users' => 'Lubatakse kasutajate modereerimine (heakskiitmine):',
		'neat_urls' => 'URLi kuju:',
		'notify_admin_q_post' => 'Uue küsimuse esitamisel saadetakse e-kiri sellele aadressile',
		'notify_users_default' => 'E-kirjaga saadetava teavituse kastike on vaikimisi märgistatud:',
		'option_default' => 'vaikimisi',
		'page_size_activity' => 'Küsimusi kõigi tegevuste lehel:',
		'page_size_ask_check_qs' => 'Maksimaalselt kuvatakse järgnev arv sarnaseid küsimusi:',
		'page_size_ask_tags' => 'Maksimaalselt kuvatakse järgnev arv siltide soovitusi:',
		'page_size_home' => 'Küsimusi avalehel:',
		'page_size_hot_qs' => 'Küsimusi kuumade küsimuste lehel:',
		'page_size_q_as' => 'Maksimaalne arv vastuseid lehe kohta:',
		'page_size_qs' => 'Küsimusi küsimuste lehel:',
		'page_size_related_qs' => 'Maksimaalne arv seostuvaid küsimusi:',
		'page_size_search' => 'Otsingutulemusi lehe kohta:',
		'page_size_tag_qs' => 'Küsimusi iga sildi lehel:',
		'page_size_tags' => 'Silte siltide lehel:',
		'page_size_una_qs' => 'Küsimusi vastuseta küsimuste lehel:',
		'page_size_users' => 'Kasutajaid edetabelis:',
		'page_size_wall' => 'Seinapostitusi lehe kohta:',
		'pages_prev_next' => 'Linke eelmistele/järgmistele lehtedele:',
		'permit_admins' => 'administraatorid',
		'permit_all' => 'igaüks',
		'permit_approve_users' => 'Registreerunud kasutajate heakskiitmine:',
		'permit_approved' => 'ainult heakskiidetud kasutajad',
		'permit_approved_points' => 'heakskiidetud kasutajad, kellel on piisavalt punkte',
		'permit_block' => 'Kasutajate või IP-de blokeerimine/taaslubamine:',
		'permit_confirmed' => 'kinnitatud e-posti aadressiga kasutajad',
		'permit_create_admins' => 'Administraatorite loomine:',
		'permit_create_eds_mods' => 'Toimetajate ja moderaatorite loomine:',
		'permit_create_experts' => 'Ekspertide loomine:',
		'permit_delete_users' => 'Kasutajate kustutamine:',
		'permit_editors' => 'toimetajad, moded ja adminnid',
		'permit_experts' => 'eksperdid, toimetajad, moded ja adminnid',
		'permit_moderators' => 'moderaatorid ja administraatorid',
		'permit_points_confirmed' => 'reganud + e-post kinnitatud + piisavalt punkte',
		'permit_points' => 'reganud + piisavalt punkte',
		'permit_see_emails' => 'Kasutajate e-posti aadressi vaatamine:',
		'permit_supers' => 'superadminnid',
		'permit_users' => 'reganud kasutajad',
		'place_full_below_content' => 'täislaiusel - sisu all',
		'place_full_below_footer' => 'täislaiusel - jaluse all',
		'place_full_below_nav' => 'täislaiusel - navigatsioonimenüü all',
		'place_full_top' => 'täislaiusel - lehe päises',
		'place_main_below_lists' => 'sisualas - nimekirjade all',
		'place_main_below_title' => 'sisualas - pealkirja all',
		'place_main_bottom' => 'sisualas - all',
		'place_main_top' => 'sisualas - üleval',
		'place_side_below_categories' => 'külgpaneelil - kategooriate all',
		'place_side_below_sidebar' => 'külgpaneelil - külgpaneeli kasti all',
		'place_side_last' => 'külgpaneelil - viimane',
		'place_side_top' => 'külgpaneelil - üleval',
		'points_a_selected' => 'Kasutaja vastus valitakse parimaks:',
		'points_a_voted_max_gain' => 'Vastuse üleshäälte limiit:',
		'points_a_voted_max_loss' => 'Vastuse mahahäälte limiit:',
		'points_base' => 'Lisatakse kõigile kasutajatele:',
		'points_multiple' => 'Korrutatakse kõiki punkte:',
		'points_per_a_voted_down' => 'Kasutaja vastus saab mahahääle:',
		'points_per_a_voted_up' => 'Kasutaja vastus saab üleshääle:',
		'points_per_q_voted_down' => 'Kasutaja küsimus saab mahahääle:',
		'points_per_q_voted_up' => 'Kasutaja küsimus saab üleshääle:',
		'points_post_a' => 'Kasutaja postitab vastuse:',
		'points_post_q' => 'Kasutaja postitab küsimuse:',
		'points_q_voted_max_gain' => 'Küsimuse üleshäälte limiit:',
		'points_q_voted_max_loss' => 'Küsimuse mahahäälte limiit:',
		'points_select_a' => 'Kasutaja valib oma küsimusele parima vastuse:',
		'points_vote_down_a' => 'Kasutaja annab vastusele mahahääle:',
		'points_vote_down_q' => 'Kasutaja annab küsimusele mahahääle:',
		'points_vote_up_a' => 'Kasutaja annab vastusele üleshääle:',
		'points_vote_up_q' => 'Kasutaja annab küsimusele üleshääle:',
		'q_urls_remove_accents' => 'Rõhumärgid eemaldatakse küsimuste URLidest:',
		'q_urls_title_length' => 'Küsimuse pealkirja pikkus URLides:',
		'register_notify_admin' => 'Uue kasutaja registreerumisel saadetakse haldajale e-kiri:',
		'search_module' => 'Kasutatakse järgnevat otsingumoodulit:',
		'show_a_form_immediate' => 'Vastamise vormi kuvatakse koheselt:',
		'show_always' => 'alati',
		'show_c_reply_buttons' => 'Kommentaaridel kuvatakse vastamise nuppu:',
		'show_custom_answer' => 'Kohandatud sõnum vastamise vormil - HTML on lubatud:',
		'show_custom_ask' => 'Kohandatud sõnum küsimuse esitamise vormil - HTML on lubatud:',
		'show_custom_comment' => 'Kohandatud sõnum kommentaari lisamise vormil - HTML on lubatud:',
		'show_custom_footer' => 'Kohandatud HTML kõigi lehtede jaluses:',
		'show_custom_header' => 'Kohandatud HTML kõigi lehtede päises:',
		'show_custom_home' => 'Kohandatud sisu avalehel viimaste küsimuste ja vastuste asemel',
		'show_custom_in_head' => 'Kohandatud HTML kõigi lehtede <head> osas:',
		'show_custom_register' => 'Kohandatud sõnum registreerumise vormil - HTML on lubatud:',
		'show_custom_sidebar' => 'Kohandatud HTML kõigi lehtede külgpaneeli kastis:',
		'show_custom_sidepanel' => 'Kohandatud HTML kõigi lehtede külgpaneelil:',
		'show_custom_welcome' => 'Kohandatud sõnum registreeruvatele kasutajatele saadetavas e-kirjas:',
		'show_fewer_cs_count' => 'Kui osaliselt peidetud, siis kuvatakse viimased:',
		'show_fewer_cs_from' => 'Kommentaarid peidetakse osaliselt pärast:',
		'show_full_date_days' => 'Täielikku kuupäeva näidatakse, kui on möödunud:',
		'show_home_description' => 'Avalehele lisatakse <meta> description info:',
		'show_if_no_as' => 'vastuste puudumisel',
		'show_message_history' => 'Privaatsõnumite ajalugu salvestatakse ja kuvatakse:',
		'show_never' => 'mitte kunagi',
		'show_notice_visitor' => 'Esmakordsetele külastajatele kuvatakse päises teavitus - HTML on lubatud:',
		'show_notice_welcome' => 'Uutele registreerunud kasutajatele kuvatakse päises teavitus - HTML on lubatud:',
		'show_selected_first' => 'Parim vastus liigutatakse üles:',
		'show_url_links' => 'Postitustes olevad URLid tuvastatakse ja teisendatakse lingiks:',
		'show_user_points' => 'Kasutajanimede järel kuvatakse punkte:',
		'show_user_titles' => 'Kasutajanimede järel kuvatakse tiitleid:',
		'show_view_counts' => 'Küsimuste nimekirjades kuvatakse vaatamiste arvu:',
		'show_view_count_q_page' => 'Küsimuste lehtedel kuvatakse vaatamiste arvu:',
		'show_when_created' => 'Kuvatakse postituste vanust:',
		'site_language' => 'Saidi keel:',
		'site_maintenance' => 'Sait lülitatakse hooldusrežiimi',
		'site_theme_mobile' => 'Teema mobiilsete seadmete jaoks:',
		'site_theme' => 'Saidi teema:',
		'site_title' => 'Q&A saidi nimi:',
		'site_url' => 'Eelistatud URL saidile:',
		'smtp_active' => 'E-kirjad saadetakse kohaliku e-posti teenuse asemel SMTP-serveri kaudu',
		'smtp_address' => 'SMTP-serveri aadress:',
		'smtp_authenticate' => 'SMTP-server nõuab kasutajat ja parooli',
		'smtp_password' => 'SMTP-serveri parool:',
		'smtp_port' => 'SMTP-serveri port:',
		'smtp_secure_none' => 'puudub',
		'smtp_secure' => 'SMTP-serveri ühenduse turvalisus:',
		'smtp_username' => 'SMTP-serveri kasutajanimi:',
		'sort_answers_by' => 'Vastused sorteeritakse:',
		'sort_time' => 'aja järgi',
		'sort_votes' => 'häälte järgi',
		'suspend_register_users' => 'Ajutiselt peatatakse kasutajaks registreerumine:',
		'tag_separator_comma' => 'Siltide ainsa eraldajana kasutatakse koma:',
		'tags_or_categories' => 'Küsimuste liigitamine:',
		'time_approved' => 'heakskiitmise aega',
		'time_written' => 'loomise aega',
		'votes_separated' => 'Üles- ja mahahääli kuvatakse eraldi:',
		'voting_on_as' => 'Vastuste hääletamine lubatakse:',
		'voting_on_q_page_only' => 'Hääletamine võimaldatakse ainult küsimuse lehel:',
		'voting_on_qs' => 'Küsimuste hääletamine lubatakse:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
