<?php
	
/*
	Question2Answer (c) Gideon Greenspan
	http://www.question2answer.org/

	Copyright (C) 2014 Sander Lepik
	
	File: qa-lang/et/qa-lang-admin.php
	Description: Language phrases for admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'active_widgets_explanation' => 'Praegu aktiivsed moodulid:',
		'add_category_button' => 'Lisa kategooria',
		'add_field_button' => 'Lisa väli',
		'add_link_button' => 'Lisa link',
		'add_link_link' => ' - ^1lisa link^2',
		'add_new_field' => 'Lisa uus väli',
		'add_new_title' => 'Lisa uus tiitel',
		'add_page_button' => 'Lisa leht',
		'add_title_button' => 'Lisa tiitel',
		'add_widget_button' => 'Lisa moodul',
		'add_widget_link' => ' - ^1lisa moodul^2',
		'admin_title' => 'Administreerimine',
		'after_footer' => 'jaluses olevate linkide järel',
		'after_main_menu' => 'peamenüü lõpus',
		'after_x_tab' => 'menüüpunkti "^" järel',
		'after_x' => '"^" järel',
		'moderate_title' => 'Modereerimine',
		'basic_editor' => 'tekst',
		'before_main_menu' => 'peamenüü ees',
		'blobs_directory_error' => 'Kaust "^", mis on defineeritud QA_BLOBS_DIRECTORY kaustana ei ole veebiserveri poolt kirjutatav.',
		'blobs_move_complete' => 'Üleslaaditud piltide ja dokumentide migreerimine on lõpetatud.',
		'blobs_move_moved' => 'Piltide ja dokumentide migreerimine: ^1/^2',
		'blobs_stop' => 'Peata migreerimine',
		'blobs_to_db' => 'Bloobid andmebaasi',
		'blobs_to_db_note' => '- kõik kettale salvestatud pildid ja dokumendid migreeritakse andmebaasi',
		'blobs_to_disk' => 'Bloobid kettale',
		'blobs_to_disk_note' => '- kõik andmebaasi salvestatud pildid ja dokumendid migreeritakse kettale',
		'block_button' => 'blokeeri',
		'block_ips_note' => 'Kasuta sidekriipsu vahemike või * kõigi numbrite jaoks. Näited: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
		'block_words_note' => 'Kõigi tähtede jaoks kasuta *. Näited: seen (leiab ainult sõna seen) , seen* (leiab seen või seened) , se*n (leiab seen, sein, selleen jne).',
		'cancel_mailing_button' => 'Katkesta kirjade saatmine',
		'categories_introduction' => 'Et kategooriatega algust teha, klõpsa nupul \'Lisa kategooria\'.',
		'categories_not_shown' => 'Mõned küsimused on kategooriates, mida ei kuvata.',
		'categories_title' => 'Kategooriad',
		'categories' => 'Katekooriad',
		'category_add_sub' => 'lisa alamkategooria',
		'category_added' => 'Kategooria on lisatud',
		'category_already_used' => 'Kategooria juba kasutab seda',
		'category_default_slug' => 'kategooria-^',
		'category_description' => 'Valikuline kategooria kirjeldus:',
		'category_max_depth_x' => 'Mõned valikud võivad olla peidetud, et takistada kategoorial ^. tasemest sügavamale minemine.',
		'category_move_parent' => 'liiguta muu ülemkategooria alla',
		'category_name_first' => 'Esimese kategooria nimi:',
		'category_name' => 'Kategooria nimi:',
		'category_no_add_subs_x' => 'Sellel kategoorial ei saa olla alamkategooriaid, sest ta on ise juba ^. taseme kategooria.',
		'category_no_delete_subs' => 'Kategooriat ei saa kustutada, sest sellel on alamkategooria.',
		'category_no_sub_error' => '^q küsimusel selles kategoorias ei ole alamkategooriat - ^1määra alamkategooria^2',
		'category_no_sub_to' => 'Alamkategooriata küsimused kategoorias "^" liigutatakse:',
		'category_no_subs' => 'Puuduvad',
		'category_none_error' => '^q küsimusel pole kategooriat - ^1määra kategooria^2',
		'category_none_to' => 'Kategooriata küsimused liigutatakse:',
		'category_parent' => 'Ülemkategooria:',
		'category_saved' => 'Kategooria on salvestatud',
		'category_slug' => 'Kategooriat tähistav fragment URLis:',
		'category_subs' => 'Alamkategooriad:',
		'category_top_level' => 'Ülemkategooriad puuduvad',
		'characters' => 'tähemärki',
		'check_language_suffix' => ' - ^1kontrolli keelefaile^2',
		'click_name_edit' => 'Kohandatud lehed või lingid:',
		'database_cleanup' => 'Andmebaasi puhastamise operatsioonid',
		'delete_category_reassign' => 'Kategooria kustutatakse ja selle küsimused liigutatakse järgmise kategooria alla:',
		'delete_category' => 'See kategooria kustutatakse',
		'delete_field' => 'See väli kustutatakse',
		'delete_hidden_complete' => 'Kõik sõltuvusteta postitused, mis on peidetud, on kustutatud',
		'delete_hidden_note' => ' - kõik peidetud küsimused, vastused ja kommentaarid, millel pole sõltuvusi',
		'delete_hidden' => 'Kustuta peidetud postitused',
		'delete_link' => 'See link kustutatakse',
		'delete_page' => 'See leht kustutatakse',
		'delete_stop' => 'Peata kustutamine',
		'delete_title' => 'See tiitel kustutatakse',
		'delete_widget_position' => 'See moodul kustutatakse sellest asukohast',
		'edit_custom_page' => 'Muuda kohandatud lehte',
		'edit_field' => ' - ^1muuda välja^2',
		'edit_link' => ' - ^1muuda linki^2',
		'edit_page' => ' - ^1muuda lehte^2',
		'edit_title' => ' - ^1muuda tiitlit^2',
		'emails_per_minute' => 'e-kirja minutis',
		'emails_title' => 'E-post',
		'feed_link_example' => 'Uudistevoo näidis',
		'feed_link' => 'Uudistevoog',
		'feeds_title' => 'RSS-uudistevood',
		'field_link_url' => 'link',
		'field_multi_line' => 'mitmerealine tekst',
		'field_name' => 'Välja nimi:',
		'field_single_line' => 'üherealine tekst',
		'field_type' => 'Sisu tüüp:',
		'first' => 'esimene',
		'flagged_title' => 'Märgistatud',
		'form_security_expired' => 'Vormi turvakood aegus - palun proovi uuesti',
		'from_anon' => 'Anonüümsetelt:',
		'from_users' => 'Kasutajatelt:',
		'general_title' => 'Üldine',
		'hidden_answers_deleted' => 'Sõltuvusteta peidetud vastuste kustutamine: ^1/^2',
		'hidden_comments_deleted' => 'Peidetud kommentaaride kustutamine: ^1/^2',
		'hidden_questions_deleted' => 'Sõltuvusteta peidetud küsimuste kustutamine: ^1/^2',
		'hotness_factors' => 'Suhteline olulisus kuumade küsimuste jaoks:',
		'hidden_title' => 'Peidetud',
		'ip_address_pages' => 'IP-aadresside lehed',
		'layout_title' => 'Kujundus',
		'link_name' => 'Lingi tekst:',
		'link_new_window' => 'Link avatakse uues aknas',
		'link_url' => 'Lingi aadress - absoluutne või suhteline Q2A juurkausta suhtes:',
		'lists_title' => 'Nimekirjad',
		'mailing_complete' => 'Kirjade saatmine on lõpetatud',
		'mailing_explanation' => 'Kasutajatel on võimalik oma konto lehe kaudu kirjadest loobuda.',
		'mailing_progress' => 'Kirjade saatmine: ^1/^2',
		'mailing_title' => 'Kirjade saatmine',
		'mailing_unsubscribe' => 'Loobumise link lisatakse kõigi kirjade lõppu.',
		'maintenance_admin_only' => 'Sait on ^1hooldusrežiimis^2 ja seega tavakasutajatele ligipääsmatu.',
		'maximum_x' => ' (maksimaalselt ^)',
		'approve_users_title' => 'Kasutajate heakskiitmine',
		'module_x_database_init' => 'Moodul ^1 ^2 vajab mõningast ^3andmebaasi algväärtustamist^4.',
		'most_flagged_title' => 'Märgistatud sisu',
		'mysql_version' => 'MySQLi versioon:',
		'nav_links_explanation' => 'Menüüs kuvatakse järgmisi linke:',
		'nav_qa_is_home' => 'Q&A (viitab avalehele)',
		'neat_urls_note' => ' (nõuab faili ^1htaccess^2)',
		'no_approve_found' => 'Heakskiiduta sisu puudub',
		'no_classification' => 'puudub',
		'no_flagged_found' => 'Märgistatud sisu ei leitud',
		'no_hidden_found' => 'Peidetud sisu ei leitud',
		'no_image_gd' => 'Paigaldatud PHP versioon kompileeriti GD mooduli toeta, seega ei saa kasutajad oma avatare otse üles laadida.',
		'no_link' => 'link puudub',
		'no_multibyte' => 'Paigaldatud PHP versioon kompileeriti multibyte stringide toeta. Otsing mitte-ASCII tähtedele pole nii efektiivne.',
		'no_privileges' => 'Ainult administraatorid omavad ligipääsu sellele lehele.',
		'no_unapproved_found' => 'Heakskiitu ootavaid kasutajaid pole',
		'not_logged_in' => 'Selle lehe vaatamiseks ^1logi sisse^2 administraatorina.',
		'opposite_main_menu' => 'peamenüü taga lõpus',
		'options_reset' => 'Seaded on lähtestatud',
		'options_saved' => 'Seaded on salvestatud',
		'options' => 'seaded',
		'page_already_used' => 'Seda kasutab juba leht',
		'page_content_html' => 'Lehel kuvatav sisu - HTML on lubatud:',
		'page_default_slug' => 'leht-^',
		'page_heading' => 'Pealkiri, mida kuvatakse lehe sisu kohal:',
		'page_name' => 'Lehe nimi (seda kasutatakse ka lingi või menüüpunkti tekstina):',
		'page_slug' => 'Lehte tähistav fragment URLis:',
		'pages_explanation' => 'Klõpsa nupul \'Lisa leht\', et lisada kohandatud sisu oma Q2A saidile või nupul \'Lisa link\', et viidata välisele veebilehele.',
		'pages_title' => 'Lehed',
		'pause_mailing_button' => 'Pane kirjade saatmine pausile',
		'per_ip_hour' => 'tunnis (IP kohta)',
		'per_user_hour' => 'tunnis (kasutaja kohta)',
		'permissions_title' => 'Õigused',
		'permit_to_view' => 'Nähtav järgnevatele kasutajatele:',
		'php_version' => 'PHP versioon:',
		'pixels' => 'pikslit',
		'plugin_module' => ' (plugin: ^)',
		'plugin_pages_explanation' => 'Pluginate abil loodavad lehed:',
		'plugins_title' => 'Pluginad',
		'points_defaults_shown' => 'Kuvatakse vaikeväärtusi, mis POLE VEEL RAKENDATUD:',
		'points_required' => 'Tiitli saamiseks on vaja koguda järgnev arv punkte:',
		'points_title' => 'Punktid',
		'points' => 'punkti',
		'position' => 'Asukoht:',
		'posting_title' => 'Postitamine',
		'profile_fields' => 'Lisaväljad kasutaja kontol või registreerumise vormil:',
		'q2a_build_date' => 'Pakendamise kuupäev:',
		'q2a_db_size' => 'Andmebaasi suurus:',
		'q2a_db_version' => 'Q2A andmebaasi versioon:',
		'q2a_latest_version' => 'Uusim versioon:',
		'q2a_version' => 'Question2Answeri versioon:',
		'question_lists' => 'Küsimuste nimekirjad',
		'question_pages' => 'Küsimuste lehed',
		'recalc_categories_backpaths' => 'Kategooriate URLide korrastamine: ^1/^2',
		'recalc_categories_complete' => 'Kõik kategooriad on edukalt korrastatud.',
		'recalc_categories_note' => ' - postituste kategooriate ja kategooriate loendurite korrastamine',
		'recalc_categories_recounting' => 'Kategooriate alla kuuluvate küsimuste üleloendamine: ^1/^2',
		'recalc_categories_updated' => 'Postituste üleloendamine: ^1/^2',
		'recalc_categories' => 'Korrasta kategooriad',
		'recalc_points_complete' => 'Kõik kasutajate punktid on edukalt korrastatud.',
		'recalc_points_note' => ' - kasutajate edetabeli ja kuvatavate punktide korrastamine',
		'recalc_points_recalced' => 'Kasutajate punktide üleloendamine: ^1/^2',
		'recalc_points_usercount' => 'Kasutajate koguarvu arvutamine...',
		'recalc_points' => 'Korrasta kasutajate punktid',
		'recalc_posts_count' => 'Küsimuste, vastuste ja kommentaaride koguarvude hankimine...',
		'recalc_stop' => 'Peata korrastamine',
		'recent_approve_title' => 'Hiljutine heakskiiduta sisu',
		'recent_hidden_title' => 'Hiljuti peidetud sisu',
		'recount_posts_as_recounted' => 'Postituste vastuste üleloendamine ja kuumuse arvutamine: ^1/^2',
		'recount_posts_complete' => 'Kõik postitused on edukalt üleloendatud ja korrastatud.',
		'recount_posts_note' => ' - antud vastuste, häälte ja märgistuste üleloendamine ning kuumuse arvutamine',
		'recount_posts_stop' => 'Peata üleloendamine',
		'recount_posts_votes_recounted' => 'Postitustele antud häälte ja märgistuste üleloendamine: ^1/^2',
		'recount_posts' => 'Korrasta postitused',
		'refill_events_complete' => 'Kõik sündmuste vood on edukalt korrastatud',
		'refill_events_note' => ' - kõigi kasutajate uuenduste vood täidetakse värske sisuga',
		'refill_events_refilled' => 'Küsimuste korrastamine: ^1/^2',
		'refill_events' => 'Korrasta uuenduste vood',
		'registration_fields' => 'lisa välju registreerumisvormile',
		'reindex_content' => 'Indekseeri sisu uuesti',
		'reindex_content_note' => ' - korrastab indeksi otsingu ja seostatud küsimuste jaoks',
		'reindex_content_stop' => 'Peata indekseerimine',
		'reindex_pages_reindexed' => 'Lehtede insekseerimine: ^1/^2',
		'reindex_posts_complete' => 'Kõik postitused on edukalt indekseeritud',
		'reindex_posts_reindexed' => 'Postituste indekseerimine: ^1/^2',
		'reindex_posts_wordcounted' => 'Sõnade üleloendamine: ^1/^2',
		'requires_php_version' => 'Keelatud - vajalik PHP ^ või uuem',
		'requires_q2a_version' => 'Keelatud - vajalik Question2Answer ^ või uuem',
		'reset_options_button' => 'Lähtesta',
		'resume_mailing_button' => 'Jätka kirjade saatmist',
		'save_options_button' => 'Salvesta seaded',
		'save_recalc_button' => 'Salvesta ja arvuta uuesti',
		'send_test_button' => 'Saada endale test kiri',
		'show_defaults_button' => 'Kuva vaikeväärtusi',
		'show_on_register_form' => 'Välja kuvatakse registreerumisvormil',
		'slug_bad_chars' => 'Fragment ei või sisaldada järgnevaid tähemärke: ^',
		'slug_reserved' => 'Fragment on reserveeritud mõne muu lehe jaoks või juba kasutusel',
		'spam_title' => 'Rämps',
		'start_mailing_button' => 'Käivita kirjade saatmine',
		'stats_title' => 'Statistika',
		'stop_recalc_warning' => 'Andmebaasi puhastamise veel käib. Kui sulged lehe, siis see tegevus katkestatakse.',
		'tag_pages' => 'Siltide lehed',
		'tags_and_categories' => 'sildid ja kategooriad',
		'tags_not_shown' => 'Mõned küsimused kasutavad silte, mida ei kuvata.',
		'tags' => 'Sildid',
		'test_sent_to_x' => 'Test kiri saadeti aadressile ^',
		'title_already_used' => 'Seda väärtust kasutab juba mingi muu tiitel',
		'top_level_categories' => 'Esimese taseme kategooriad:',
		'total_as' => 'Vastuseid kokku:',
		'total_cs' => 'Kommentaare kokku:',
		'total_qs' => 'Küsimusi kokku:',
		'unnamed_plugin' => 'Nimetu plugin',
		'upgrade_db' => 'Question2Answeri andmebaasi tuleb selle versiooni jaoks ^1uuendada^2.',
		'url_format_note' => 'Valikud, mis on tähistatud märgiga ^ on selle saidi häälestusega kasutatavad. Parimaks tulemuseks otsingumootoritega (SEO) kasuta esimest saadaolevat ^ märgiga valikut.',
		'user_pages' => 'Kasutajate lehed',
		'user_title' => 'Kasutaja tiitel - HTML on lubatud:',
		'user_titles' => 'Punktidel baseeruvad kasutajate tiitlid:',
		'users_active' => 'Aktiivseid kasutajaid:',
		'users_must_have' => 'kasutajatel peab olema vähemalt',
		'users_posted' => 'Postitusi teinud kasutajaid:',
		'users_registered' => 'Registreerunud kasutajaid:',
		'users_title' => 'Kasutajad',
		'users_voted' => 'Hääli andnud kasutajaid:',
		'version_get_x' => 'hangi versioon ^',
		'version_requires_php' => '^1 nõuab PHP versiooni ^2', 
		'version_requires_q2a' => '^1 nõuab Q2A versiooni ^2', 
		'version_latest_unknown' => 'uusim pole teada',
		'version_latest' => 'uusim',
		'viewing_title' => 'Vaatamine',
		'widget_all_pages' => 'Mooduleid kuvatakse selles asukohas kõigil võimalikel lehtedel',
		'widget_global_options' => ' - ^1seaded^2',
		'widget_name' => 'Mooduli nimi:',
		'widget_no_positions' => 'See moodul on juba kõigisse võimalikesse asukohtadesse lisatud.',
		'widget_not_available' => 'See moodul pole saadaval. Põhjuseks võib olla see, et moodulit pakkuv plugin pole enam paigaldatud.',
		'widget_pages_explanation' => 'Moodulit kuvatakse selles asukohas järgnevatel lehtedel:',
		'widgets_explanation' => 'Saadaolevad moodulid:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
