<?php
	
/*
	Question2Answer (c) Gideon Greenspan
	http://www.question2answer.org/

	Copyright (C) 2013-2014 Sander Lepik
	
	File: qa-lang/et/qa-lang-question.php
	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer_title' => '1 vastus',
		'a_convert_to_c_on' => 'Muuda see vastus kommentaariks:',
		'a_convert_to_c' => 'Muuda see vastus kommentaariks',
		'a_convert_warn_cs' => 'Hoiatus: seda muudatust ei saa tagasi pöörata ning lisaks vastusele liigutatakse ka vastuse kommentaarid.',
		'a_convert_warn' => 'Hoiatus: seda muudatust ei saa tagasi pöörata.',
		'a_notify_email' => 'Saadetakse e-kiri sellele aadressile, kui vastus valitakse parimaks või sellele lisatakse kommentaar:',
		'a_notify_label' => 'Saadetakse e-kiri, kui vastus valitakse parimaks või sellele lisatakse kommentaar',
		'a_notify_x_label' => 'Saadetakse e-kiri (aadressile ^), kui vastus valitakse parimaks või sellele lisatakse kommentaar',
		'a_waiting_your_approval' => 'See vastus ootab sinult heakskiitu',
		'a_your_waiting_approval' => 'Sinu vastust kontrollitakse õige pea.',
		'add_answer_button' => 'Lisa vastus',
		'add_comment_button' => 'Lisa kommentaar',
		'add_q_favorites' => 'Lisa see küsimus lemmikutesse',
		'anon_name_label' => 'Kuvatav nimi (valikuline):',
		'answer_button' => 'vasta',
		'answer_limit' => 'Liiga palju vastuseid vastu võetud - palun proovi tunni pärast uuesti',
		'answer_must_be_approved' => 'Enne küsimusele vastamist peab konto olema saanud heakskiidu.',
		'answer_must_confirm' => 'Küsimusele vastamiseks ^5kinnita oma e-posti aadress^6.',
		'answer_must_login' => 'Küsimusele vastamiseks ^1logi sisse^2 või ^3registreeru^4.',
		'answer_q_popup' => 'Vasta sellele küsimusele',
		'approve_button' => 'kiida heaks',
		'ask_button' => 'Esita küsimus',
		'ask_follow_from_a' => 'Sinu küsimus on seotud järgneva vastusega:',
		'ask_follow_title' => 'Küsi seostuv küsimus',
		'ask_limit' => 'Liiga palju küsimusi vastu võetud - palun proovi tunni pärast uuesti',
		'ask_must_be_approved' => 'Enne küsimuse esitamist peab sinu konto olema saanud heakskiidu.',
		'ask_must_confirm' => 'Küsimuse esitamiseks ^5kinnita oma e-posti aadress^6.',
		'ask_must_login' => 'Küsimuse esitamiseks ^1logi sisse^2 või ^3registreeru^4.',
		'ask_same_q' => 'Enne jätkamist kontrolli palun, et see küsimus pole juba küsitud:',
		'ask_title' => 'Küsimuse esitamine',
		'c_notify_email' => 'Saadetakse e-kiri sellele aadressile, kui minu kommentaari järele lisatakse veel kommentaare:',
		'c_notify_label' => 'Saadetakse e-kiri, kui minu kommentaari järele lisatakse veel kommentaare',
		'c_notify_x_label' => 'Saadetakse e-kiri aadressile (^), kui minu kommentaari järele lisatakse veel kommentaare',
		'c_waiting_your_approval' => 'See kommentaar ootab heakskiitu',
		'c_your_waiting_approval' => 'Sinu kommentaari kontrollitakse õige pea.',
		'category_js_note' => 'Kategooriate valimiseks luba brauseris javascripti kasutamine.',
		'category_required' => 'Palun vali kategooria',
		'category_ask_not_allowed' => 'Sul pole õigust selles kategoorias küsimusi esitada',
		'claim_button' => 'Mina kirjutasin selle',
		'clear_flags_button' => 'puhasta märgistused',
		'clear_flags_popup' => 'Eemalda kõigi kasutajate poolt lisatud märgistused',
		'close_button' => 'sulge',
		'close_duplicate_error' => 'Algset küsimust ei leitud - palun proovi uuesti sisestada algse küsimuse number URList, nt 123.',
		'close_duplicate' => 'See küsimus on korduv',
		'close_form_button' => 'Sulge küsimus',
		'close_form_title' => 'Küsimuse sulgemine',
		'close_original_note' => 'Võid sisestada ka küsimuse numbri URList, nt 123.',
		'close_original_title' => 'Algse küsimuse URL:',
		'close_q_popup' => 'Küsimuse sulgemine uutele vastustele',
		'close_reason_title' => 'Küsimuse sulgemise põhjus:',
		'closed_as_duplicate' => 'suletud, kordab järgnevat küsimust:',
		'closed_with_note' => 'suletud järgneva märkusega:',
		'comment_a_popup' => 'Kommentaari lisamine sellele vastusele',
		'comment_button' => 'kommenteeri',
		'comment_limit' => 'Liiga palju kommentaare vastu võetud - palun proovi tunni pärast uuesti',
		'comment_must_be_approved' => 'Kommenteerimiseks peab konto olema saanud heakskiidu.',
		'comment_must_confirm' => 'Kommenteerimiseks ^5kinnita palun oma e-posti aadress^6.',
		'comment_must_login' => 'Kommenteerimiseks ^1logi sisse^2 või ^3registreeru^4.',
		'comment_on_a' => 'vastusele: ',
		'comment_on_q' => 'küsimusele: ',
		'comment_q_popup' => 'Kommentaari lisamine sellele küsimusele',
		'delete_a_popup' => 'Vastuse kustutamine jäädavalt',
		'delete_button' => 'kustuta',
		'delete_c_popup' => 'Kommentaari kustutamine jäädavalt',
		'delete_q_popup' => 'Küsimuse kustutamine jäädavalt',
		'duplicate_content' => 'Sinu sisestatu näib korduvat.',
		'edit_a_popup' => 'Selle vastuse muutmine',
		'edit_a_title' => 'Vastuse muutmine',
		'edit_button' => 'muuda',
		'edit_c_popup' => 'Selle kommentaari muutmine',
		'edit_c_title' => 'Kommentaari muutmine',
		'edit_must_confirm' => 'Muutmiseks ^5kinnita palun oma e-posti aadress^6.',
		'edit_must_login' => 'Muutmiseks ^1logi sisse^2 või ^3registreeru^4.',
		'edit_q_popup' => 'Selle küsimuse muutmine',
		'edit_q_title' => 'Küsimuse muutmine',
		'example_tags' => 'Näidissildid: ',
		'flag_a_popup' => 'Vastuse märgistamine rämpsuks või ebasobivaks',
		'flag_button' => 'märgista',
		'flag_c_popup' => 'Kommentaari märgistamine rämpsuks või ebasobivaks',
		'flag_hide_button' => 'märgista ja peida',
		'flag_limit' => 'Liiga palju posituste märgistamisi - palun proovi tunni pärast uuesti',
		'flag_must_confirm' => 'Märgistamiseks ^5kinnita palun oma e-posti aadress^6.',
		'flag_must_login' => 'Posituste märgistamiseks ^1logi sisse^2 või ^3registreeru^4.',
		'flag_not_allowed' => 'Selle märgistamine pole lubatud',
		'flag_q_popup' => 'Küsimuse märgistamine rämpsuks või ebasobivaks',
		'follow_a_popup' => 'Uue selle vastusega seostuva küsimuse küsimine',
		'follow_button' => 'esita seostuv küsimus',
		'follows_a' => 'seostub vastusega järgnevale küsimusele:',
		'follows_q' => 'seostub järgneva küsimusega:',
		'hide_a_popup' => 'Selle vastuse peitmine',
		'hide_button' => 'peida',
		'hide_c_popup' => 'Selle kommentaari peitmine',
		'hide_q_popup' => 'Selle küsimuse peitmine',
		'matching_tags' => 'Sobivad sildid: ',
		'max_tags_x' => 'Lubatud on maksimaalselt ^ silti',
		'min_tags_x' => 'Palun lisa vähemalt ^ silt(i)',
		'notify_email_note' => 'Privaatsusest: sinu e-posti aadressi kasutatakse ainult nende teavituste saatmiseks.',
		'q_category_label' => 'Kategooria:',
		'q_content_label' => 'Rohkem infot küsimuse kohta:',
		'q_hidden_author' => 'See küsimus on autori poolt peidetud',
		'q_hidden_flagged' => 'See küsimus on märgistatud ja peidetud',
		'q_hidden_other' => 'See küsimus on peidetud',
		'q_notify_email' => 'Saadetakse e-kiri sellele aadressile, kui minu küsimusele vastatakse või sellele lisatakse kommentaar:',
		'q_notify_label' => 'Saadetakse e-kiri, kui minu küsimusele vastatakse või sellele lisatakse kommentaar',
		'q_notify_x_label' => 'Saadetakse e-kiri (aadressile ^), kui minu küsimusele vastatakse või sellele lisatakse kommentaar',
		'q_tags_comma_label' => 'Sildid - eraldamiseks kasuta koma (,):',
		'q_tags_label' => 'Sildid - sõnade sidumiseks kasuta sidekriipse:',
		'q_title_label' => 'Küsimus ühe lausega:',
		'q_waiting_approval' => 'Küsimus ootab heakskiitu',
		'q_waiting_your_approval' => 'Küsimus ootab sinu heakskiitu',
		'q_your_waiting_approval' => 'Sinu küsimust kontrollitakse õige pea.',
		'recat_button' => 'muuda kategooriat',
		'recat_popup' => 'Selle küsimuse kategooria muutmine',
		'recat_q_title' => 'Küsimuse kategooria muutmine',
		'reject_button' => 'lükka tagasi',
		'remove_q_favorites' => 'Eemalda see küsimus lemmikutest',
		'reopen_button' => 'ava uuesti',
		'reply_button' => 'vasta',
		'reply_c_popup' => 'Vastamine sellele kommentaarile',
		'reshow_button' => 'kuva uuesti',
		'retag_button' => 'muuda silte',
		'retag_cat_popup' => 'Selle küsimuse kategooria või siltide muutmine',
		'retag_popup' => 'Selle küsimuse siltide muutmine',
		'retag_q_title' => 'Küsimuse siltide muutmine',
		'save_silent_label' => 'Muudetakse salamisi, nii et sellest ei jääks märki', 
		'select_popup' => 'Klõpsa, et valida parimaks vastuseks',
		'select_text' => 'Parim vastus',
		'show_1_comment' => 'Kuva 1 kommentaar',
		'show_1_previous_comment' => 'Kuva 1 eelmine kommentaar',
		'show_x_comments' => 'Kuva ^ kommentaari',
		'show_x_previous_comments' => 'Kuva ^ eelmist kommentaari',
		'unflag_button' => 'eemalda märgistus',
		'unflag_popup' => 'Lisatud märgistuse eemaldamine',
		'unselect_popup' => 'Parimaks valimise eemaldamiseks klõpsa',
		'x_answers_title' => '^ vastust',
		'your_answer_title' => 'Sinu vastus',
		'your_comment_a' => 'Sinu kommentaar järgnevale vastusele:',
		'your_comment_q' => 'Sinu kommentaar järgnevale küsimusele:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
